version: '3.8'

services:
  backend:
    build: .
    container_name: task-manager-api
    ports:
      - "${PORT}:3333"
    env_file:
      - ./.env
    volumes:
      - ./database.db:/app/database.db
    restart: unless-stopped
